name: Build Marahel Library
on: [push]

jobs:
  build_marahel:
    name: Build Marahel to JS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the current repo
        uses: actions/checkout@v2
        
      - name: Setup Node.js Environment
        uses: actions/setup-node@v2
        
      - name: Setup typescript
        run: npm install typescript
        
      - name: Build Marahel
        run: tsc -d --outFile bin/Marahel.js
      
      - name: Add build libraries
        run: |
          cd bin
          ls
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add *
          git commit -m "Automatically Build Library"
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
